// Code generated by MockGen. DO NOT EDIT.
// Source: internals/onboarding/interfaces/project_service.go
//
// Generated by this command:
//
//	mockgen -source=internals/onboarding/interfaces/project_service.go -destination=internals/onboarding/mocks/project_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	onboardingv1 "github.com/ralvescosta/costa-financial-assistant/backend/protos/generated/onboarding/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockProjectMembersService is a mock of ProjectMembersService interface.
type MockProjectMembersService struct {
	ctrl     *gomock.Controller
	recorder *MockProjectMembersServiceMockRecorder
	isgomock struct{}
}

// MockProjectMembersServiceMockRecorder is the mock recorder for MockProjectMembersService.
type MockProjectMembersServiceMockRecorder struct {
	mock *MockProjectMembersService
}

// NewMockProjectMembersService creates a new mock instance.
func NewMockProjectMembersService(ctrl *gomock.Controller) *MockProjectMembersService {
	mock := &MockProjectMembersService{ctrl: ctrl}
	mock.recorder = &MockProjectMembersServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectMembersService) EXPECT() *MockProjectMembersServiceMockRecorder {
	return m.recorder
}

// CreateProject mocks base method.
func (m *MockProjectMembersService) CreateProject(ctx context.Context, ownerID, name string, projectType onboardingv1.ProjectType) (*onboardingv1.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProject", ctx, ownerID, name, projectType)
	ret0, _ := ret[0].(*onboardingv1.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProject indicates an expected call of CreateProject.
func (mr *MockProjectMembersServiceMockRecorder) CreateProject(ctx, ownerID, name, projectType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProject", reflect.TypeOf((*MockProjectMembersService)(nil).CreateProject), ctx, ownerID, name, projectType)
}

// GetProject mocks base method.
func (m *MockProjectMembersService) GetProject(ctx context.Context, projectID string) (*onboardingv1.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProject", ctx, projectID)
	ret0, _ := ret[0].(*onboardingv1.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProject indicates an expected call of GetProject.
func (mr *MockProjectMembersServiceMockRecorder) GetProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProject", reflect.TypeOf((*MockProjectMembersService)(nil).GetProject), ctx, projectID)
}

// InviteProjectMember mocks base method.
func (m *MockProjectMembersService) InviteProjectMember(ctx context.Context, projectID, inviteeEmail string, role onboardingv1.ProjectMemberRole, invitedBy string) (*onboardingv1.ProjectMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InviteProjectMember", ctx, projectID, inviteeEmail, role, invitedBy)
	ret0, _ := ret[0].(*onboardingv1.ProjectMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InviteProjectMember indicates an expected call of InviteProjectMember.
func (mr *MockProjectMembersServiceMockRecorder) InviteProjectMember(ctx, projectID, inviteeEmail, role, invitedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InviteProjectMember", reflect.TypeOf((*MockProjectMembersService)(nil).InviteProjectMember), ctx, projectID, inviteeEmail, role, invitedBy)
}

// ListProjectMembers mocks base method.
func (m *MockProjectMembersService) ListProjectMembers(ctx context.Context, projectID string, pageSize int32, pageToken string) ([]*onboardingv1.ProjectMember, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectMembers", ctx, projectID, pageSize, pageToken)
	ret0, _ := ret[0].([]*onboardingv1.ProjectMember)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListProjectMembers indicates an expected call of ListProjectMembers.
func (mr *MockProjectMembersServiceMockRecorder) ListProjectMembers(ctx, projectID, pageSize, pageToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectMembers", reflect.TypeOf((*MockProjectMembersService)(nil).ListProjectMembers), ctx, projectID, pageSize, pageToken)
}

// UpdateProjectMemberRole mocks base method.
func (m *MockProjectMembersService) UpdateProjectMemberRole(ctx context.Context, projectID, memberID string, newRole onboardingv1.ProjectMemberRole) (*onboardingv1.ProjectMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProjectMemberRole", ctx, projectID, memberID, newRole)
	ret0, _ := ret[0].(*onboardingv1.ProjectMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProjectMemberRole indicates an expected call of UpdateProjectMemberRole.
func (mr *MockProjectMembersServiceMockRecorder) UpdateProjectMemberRole(ctx, projectID, memberID, newRole any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProjectMemberRole", reflect.TypeOf((*MockProjectMembersService)(nil).UpdateProjectMemberRole), ctx, projectID, memberID, newRole)
}

// MockProjectMembersRepository is a mock of ProjectMembersRepository interface.
type MockProjectMembersRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectMembersRepositoryMockRecorder
	isgomock struct{}
}

// MockProjectMembersRepositoryMockRecorder is the mock recorder for MockProjectMembersRepository.
type MockProjectMembersRepositoryMockRecorder struct {
	mock *MockProjectMembersRepository
}

// NewMockProjectMembersRepository creates a new mock instance.
func NewMockProjectMembersRepository(ctrl *gomock.Controller) *MockProjectMembersRepository {
	mock := &MockProjectMembersRepository{ctrl: ctrl}
	mock.recorder = &MockProjectMembersRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectMembersRepository) EXPECT() *MockProjectMembersRepositoryMockRecorder {
	return m.recorder
}

// CreateMember mocks base method.
func (m *MockProjectMembersRepository) CreateMember(ctx context.Context, projectID, userID, invitedBy, role string) (*onboardingv1.ProjectMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMember", ctx, projectID, userID, invitedBy, role)
	ret0, _ := ret[0].(*onboardingv1.ProjectMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMember indicates an expected call of CreateMember.
func (mr *MockProjectMembersRepositoryMockRecorder) CreateMember(ctx, projectID, userID, invitedBy, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMember", reflect.TypeOf((*MockProjectMembersRepository)(nil).CreateMember), ctx, projectID, userID, invitedBy, role)
}

// CreateProject mocks base method.
func (m *MockProjectMembersRepository) CreateProject(ctx context.Context, ownerID, name, projectType string) (*onboardingv1.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProject", ctx, ownerID, name, projectType)
	ret0, _ := ret[0].(*onboardingv1.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProject indicates an expected call of CreateProject.
func (mr *MockProjectMembersRepositoryMockRecorder) CreateProject(ctx, ownerID, name, projectType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProject", reflect.TypeOf((*MockProjectMembersRepository)(nil).CreateProject), ctx, ownerID, name, projectType)
}

// FindMemberByID mocks base method.
func (m *MockProjectMembersRepository) FindMemberByID(ctx context.Context, projectID, memberID string) (*onboardingv1.ProjectMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMemberByID", ctx, projectID, memberID)
	ret0, _ := ret[0].(*onboardingv1.ProjectMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMemberByID indicates an expected call of FindMemberByID.
func (mr *MockProjectMembersRepositoryMockRecorder) FindMemberByID(ctx, projectID, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMemberByID", reflect.TypeOf((*MockProjectMembersRepository)(nil).FindMemberByID), ctx, projectID, memberID)
}

// FindUserByEmail mocks base method.
func (m *MockProjectMembersRepository) FindUserByEmail(ctx context.Context, email string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByEmail", ctx, email)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByEmail indicates an expected call of FindUserByEmail.
func (mr *MockProjectMembersRepositoryMockRecorder) FindUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByEmail", reflect.TypeOf((*MockProjectMembersRepository)(nil).FindUserByEmail), ctx, email)
}

// GetProject mocks base method.
func (m *MockProjectMembersRepository) GetProject(ctx context.Context, projectID string) (*onboardingv1.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProject", ctx, projectID)
	ret0, _ := ret[0].(*onboardingv1.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProject indicates an expected call of GetProject.
func (mr *MockProjectMembersRepositoryMockRecorder) GetProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProject", reflect.TypeOf((*MockProjectMembersRepository)(nil).GetProject), ctx, projectID)
}

// ListMembers mocks base method.
func (m *MockProjectMembersRepository) ListMembers(ctx context.Context, projectID string, pageSize int32, pageToken string) ([]*onboardingv1.ProjectMember, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", ctx, projectID, pageSize, pageToken)
	ret0, _ := ret[0].([]*onboardingv1.ProjectMember)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockProjectMembersRepositoryMockRecorder) ListMembers(ctx, projectID, pageSize, pageToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockProjectMembersRepository)(nil).ListMembers), ctx, projectID, pageSize, pageToken)
}

// UpdateMemberRole mocks base method.
func (m *MockProjectMembersRepository) UpdateMemberRole(ctx context.Context, projectID, memberID, newRole string) (*onboardingv1.ProjectMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMemberRole", ctx, projectID, memberID, newRole)
	ret0, _ := ret[0].(*onboardingv1.ProjectMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMemberRole indicates an expected call of UpdateMemberRole.
func (mr *MockProjectMembersRepositoryMockRecorder) UpdateMemberRole(ctx, projectID, memberID, newRole any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMemberRole", reflect.TypeOf((*MockProjectMembersRepository)(nil).UpdateMemberRole), ctx, projectID, memberID, newRole)
}
