// Code generated by MockGen. DO NOT EDIT.
// Source: internals/payments/interfaces/payment_cycle_service.go
//
// Generated by this command:
//
//	mockgen -source=internals/payments/interfaces/payment_cycle_service.go -destination=internals/payments/mocks/cycle_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	interfaces "github.com/ralvescosta/costa-financial-assistant/backend/internals/payments/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentCycleService is a mock of PaymentCycleService interface.
type MockPaymentCycleService struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentCycleServiceMockRecorder
	isgomock struct{}
}

// MockPaymentCycleServiceMockRecorder is the mock recorder for MockPaymentCycleService.
type MockPaymentCycleServiceMockRecorder struct {
	mock *MockPaymentCycleService
}

// NewMockPaymentCycleService creates a new mock instance.
func NewMockPaymentCycleService(ctrl *gomock.Controller) *MockPaymentCycleService {
	mock := &MockPaymentCycleService{ctrl: ctrl}
	mock.recorder = &MockPaymentCycleServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentCycleService) EXPECT() *MockPaymentCycleServiceMockRecorder {
	return m.recorder
}

// GetCyclePreference mocks base method.
func (m *MockPaymentCycleService) GetCyclePreference(ctx context.Context, projectID string) (*interfaces.CyclePreference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCyclePreference", ctx, projectID)
	ret0, _ := ret[0].(*interfaces.CyclePreference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCyclePreference indicates an expected call of GetCyclePreference.
func (mr *MockPaymentCycleServiceMockRecorder) GetCyclePreference(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCyclePreference", reflect.TypeOf((*MockPaymentCycleService)(nil).GetCyclePreference), ctx, projectID)
}

// UpsertCyclePreference mocks base method.
func (m *MockPaymentCycleService) UpsertCyclePreference(ctx context.Context, projectID string, dayOfMonth int, updatedBy string) (*interfaces.CyclePreference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCyclePreference", ctx, projectID, dayOfMonth, updatedBy)
	ret0, _ := ret[0].(*interfaces.CyclePreference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertCyclePreference indicates an expected call of UpsertCyclePreference.
func (mr *MockPaymentCycleServiceMockRecorder) UpsertCyclePreference(ctx, projectID, dayOfMonth, updatedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCyclePreference", reflect.TypeOf((*MockPaymentCycleService)(nil).UpsertCyclePreference), ctx, projectID, dayOfMonth, updatedBy)
}

// MockPaymentCycleRepository is a mock of PaymentCycleRepository interface.
type MockPaymentCycleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentCycleRepositoryMockRecorder
	isgomock struct{}
}

// MockPaymentCycleRepositoryMockRecorder is the mock recorder for MockPaymentCycleRepository.
type MockPaymentCycleRepositoryMockRecorder struct {
	mock *MockPaymentCycleRepository
}

// NewMockPaymentCycleRepository creates a new mock instance.
func NewMockPaymentCycleRepository(ctrl *gomock.Controller) *MockPaymentCycleRepository {
	mock := &MockPaymentCycleRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentCycleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentCycleRepository) EXPECT() *MockPaymentCycleRepositoryMockRecorder {
	return m.recorder
}

// GetByProjectID mocks base method.
func (m *MockPaymentCycleRepository) GetByProjectID(ctx context.Context, projectID string) (*interfaces.CyclePreference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProjectID", ctx, projectID)
	ret0, _ := ret[0].(*interfaces.CyclePreference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProjectID indicates an expected call of GetByProjectID.
func (mr *MockPaymentCycleRepositoryMockRecorder) GetByProjectID(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProjectID", reflect.TypeOf((*MockPaymentCycleRepository)(nil).GetByProjectID), ctx, projectID)
}

// Upsert mocks base method.
func (m *MockPaymentCycleRepository) Upsert(ctx context.Context, projectID string, dayOfMonth int, updatedBy string) (*interfaces.CyclePreference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, projectID, dayOfMonth, updatedBy)
	ret0, _ := ret[0].(*interfaces.CyclePreference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockPaymentCycleRepositoryMockRecorder) Upsert(ctx, projectID, dayOfMonth, updatedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockPaymentCycleRepository)(nil).Upsert), ctx, projectID, dayOfMonth, updatedBy)
}
