// Code generated by MockGen. DO NOT EDIT.
// Source: ./internals/payments/interfaces/history_repository.go
//
// Generated by this command:
//
//	mockgen -source=./internals/payments/interfaces/history_repository.go -destination=./internals/payments/mocks/history_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	interfaces "github.com/ralvescosta/costa-financial-assistant/backend/internals/payments/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockHistoryRepository is a mock of HistoryRepository interface.
type MockHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockHistoryRepositoryMockRecorder
	isgomock struct{}
}

// MockHistoryRepositoryMockRecorder is the mock recorder for MockHistoryRepository.
type MockHistoryRepositoryMockRecorder struct {
	mock *MockHistoryRepository
}

// NewMockHistoryRepository creates a new mock instance.
func NewMockHistoryRepository(ctrl *gomock.Controller) *MockHistoryRepository {
	mock := &MockHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistoryRepository) EXPECT() *MockHistoryRepositoryMockRecorder {
	return m.recorder
}

// GetCategoryBreakdown mocks base method.
func (m *MockHistoryRepository) GetCategoryBreakdown(ctx context.Context, projectID string, months int) ([]interfaces.CategoryBreakdownEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryBreakdown", ctx, projectID, months)
	ret0, _ := ret[0].([]interfaces.CategoryBreakdownEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryBreakdown indicates an expected call of GetCategoryBreakdown.
func (mr *MockHistoryRepositoryMockRecorder) GetCategoryBreakdown(ctx, projectID, months any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryBreakdown", reflect.TypeOf((*MockHistoryRepository)(nil).GetCategoryBreakdown), ctx, projectID, months)
}

// GetComplianceMetrics mocks base method.
func (m *MockHistoryRepository) GetComplianceMetrics(ctx context.Context, projectID string, months int) ([]interfaces.MonthlyComplianceEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComplianceMetrics", ctx, projectID, months)
	ret0, _ := ret[0].([]interfaces.MonthlyComplianceEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComplianceMetrics indicates an expected call of GetComplianceMetrics.
func (mr *MockHistoryRepositoryMockRecorder) GetComplianceMetrics(ctx, projectID, months any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComplianceMetrics", reflect.TypeOf((*MockHistoryRepository)(nil).GetComplianceMetrics), ctx, projectID, months)
}

// GetTimeline mocks base method.
func (m *MockHistoryRepository) GetTimeline(ctx context.Context, projectID string, months int) ([]interfaces.MonthlyTimelineEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTimeline", ctx, projectID, months)
	ret0, _ := ret[0].([]interfaces.MonthlyTimelineEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTimeline indicates an expected call of GetTimeline.
func (mr *MockHistoryRepositoryMockRecorder) GetTimeline(ctx, projectID, months any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTimeline", reflect.TypeOf((*MockHistoryRepository)(nil).GetTimeline), ctx, projectID, months)
}
