// Code generated by MockGen. DO NOT EDIT.
// Source: internals/payments/interfaces/reconciliation_service.go
//
// Generated by this command:
//
//	mockgen -source=internals/payments/interfaces/reconciliation_service.go -destination=internals/payments/mocks/reconciliation_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	interfaces "github.com/ralvescosta/costa-financial-assistant/backend/internals/payments/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockReconciliationService is a mock of ReconciliationService interface.
type MockReconciliationService struct {
	ctrl     *gomock.Controller
	recorder *MockReconciliationServiceMockRecorder
	isgomock struct{}
}

// MockReconciliationServiceMockRecorder is the mock recorder for MockReconciliationService.
type MockReconciliationServiceMockRecorder struct {
	mock *MockReconciliationService
}

// NewMockReconciliationService creates a new mock instance.
func NewMockReconciliationService(ctrl *gomock.Controller) *MockReconciliationService {
	mock := &MockReconciliationService{ctrl: ctrl}
	mock.recorder = &MockReconciliationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReconciliationService) EXPECT() *MockReconciliationServiceMockRecorder {
	return m.recorder
}

// AutoReconcile mocks base method.
func (m *MockReconciliationService) AutoReconcile(ctx context.Context, projectID, statementID string) (*interfaces.ReconciliationSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AutoReconcile", ctx, projectID, statementID)
	ret0, _ := ret[0].(*interfaces.ReconciliationSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AutoReconcile indicates an expected call of AutoReconcile.
func (mr *MockReconciliationServiceMockRecorder) AutoReconcile(ctx, projectID, statementID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutoReconcile", reflect.TypeOf((*MockReconciliationService)(nil).AutoReconcile), ctx, projectID, statementID)
}

// CreateManualLink mocks base method.
func (m *MockReconciliationService) CreateManualLink(ctx context.Context, projectID, transactionLineID, billRecordID, linkedBy string) (*interfaces.ReconciliationLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateManualLink", ctx, projectID, transactionLineID, billRecordID, linkedBy)
	ret0, _ := ret[0].(*interfaces.ReconciliationLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateManualLink indicates an expected call of CreateManualLink.
func (mr *MockReconciliationServiceMockRecorder) CreateManualLink(ctx, projectID, transactionLineID, billRecordID, linkedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateManualLink", reflect.TypeOf((*MockReconciliationService)(nil).CreateManualLink), ctx, projectID, transactionLineID, billRecordID, linkedBy)
}

// GetSummary mocks base method.
func (m *MockReconciliationService) GetSummary(ctx context.Context, projectID, periodStart, periodEnd string) (*interfaces.ReconciliationSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummary", ctx, projectID, periodStart, periodEnd)
	ret0, _ := ret[0].(*interfaces.ReconciliationSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummary indicates an expected call of GetSummary.
func (mr *MockReconciliationServiceMockRecorder) GetSummary(ctx, projectID, periodStart, periodEnd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummary", reflect.TypeOf((*MockReconciliationService)(nil).GetSummary), ctx, projectID, periodStart, periodEnd)
}

// MockReconciliationRepository is a mock of ReconciliationRepository interface.
type MockReconciliationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReconciliationRepositoryMockRecorder
	isgomock struct{}
}

// MockReconciliationRepositoryMockRecorder is the mock recorder for MockReconciliationRepository.
type MockReconciliationRepositoryMockRecorder struct {
	mock *MockReconciliationRepository
}

// NewMockReconciliationRepository creates a new mock instance.
func NewMockReconciliationRepository(ctrl *gomock.Controller) *MockReconciliationRepository {
	mock := &MockReconciliationRepository{ctrl: ctrl}
	mock.recorder = &MockReconciliationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReconciliationRepository) EXPECT() *MockReconciliationRepositoryMockRecorder {
	return m.recorder
}

// CreateLink mocks base method.
func (m *MockReconciliationRepository) CreateLink(ctx context.Context, link interfaces.ReconciliationLink) (*interfaces.ReconciliationLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLink", ctx, link)
	ret0, _ := ret[0].(*interfaces.ReconciliationLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLink indicates an expected call of CreateLink.
func (mr *MockReconciliationRepositoryMockRecorder) CreateLink(ctx, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLink", reflect.TypeOf((*MockReconciliationRepository)(nil).CreateLink), ctx, link)
}

// GetBillsForPeriod mocks base method.
func (m *MockReconciliationRepository) GetBillsForPeriod(ctx context.Context, projectID, periodStart, periodEnd string) ([]interfaces.ReconciliationSummaryEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBillsForPeriod", ctx, projectID, periodStart, periodEnd)
	ret0, _ := ret[0].([]interfaces.ReconciliationSummaryEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBillsForPeriod indicates an expected call of GetBillsForPeriod.
func (mr *MockReconciliationRepositoryMockRecorder) GetBillsForPeriod(ctx, projectID, periodStart, periodEnd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBillsForPeriod", reflect.TypeOf((*MockReconciliationRepository)(nil).GetBillsForPeriod), ctx, projectID, periodStart, periodEnd)
}

// GetSummary mocks base method.
func (m *MockReconciliationRepository) GetSummary(ctx context.Context, projectID, periodStart, periodEnd string) (*interfaces.ReconciliationSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummary", ctx, projectID, periodStart, periodEnd)
	ret0, _ := ret[0].(*interfaces.ReconciliationSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummary indicates an expected call of GetSummary.
func (mr *MockReconciliationRepositoryMockRecorder) GetSummary(ctx, projectID, periodStart, periodEnd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummary", reflect.TypeOf((*MockReconciliationRepository)(nil).GetSummary), ctx, projectID, periodStart, periodEnd)
}

// GetUnmatchedTransactionLines mocks base method.
func (m *MockReconciliationRepository) GetUnmatchedTransactionLines(ctx context.Context, projectID, statementID string) ([]interfaces.ReconciliationSummaryEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnmatchedTransactionLines", ctx, projectID, statementID)
	ret0, _ := ret[0].([]interfaces.ReconciliationSummaryEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnmatchedTransactionLines indicates an expected call of GetUnmatchedTransactionLines.
func (mr *MockReconciliationRepositoryMockRecorder) GetUnmatchedTransactionLines(ctx, projectID, statementID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnmatchedTransactionLines", reflect.TypeOf((*MockReconciliationRepository)(nil).GetUnmatchedTransactionLines), ctx, projectID, statementID)
}

// UpdateTransactionStatus mocks base method.
func (m *MockReconciliationRepository) UpdateTransactionStatus(ctx context.Context, projectID, transactionLineID string, status interfaces.TransactionReconciliationStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransactionStatus", ctx, projectID, transactionLineID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTransactionStatus indicates an expected call of UpdateTransactionStatus.
func (mr *MockReconciliationRepositoryMockRecorder) UpdateTransactionStatus(ctx, projectID, transactionLineID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransactionStatus", reflect.TypeOf((*MockReconciliationRepository)(nil).UpdateTransactionStatus), ctx, projectID, transactionLineID, status)
}
