// Code generated by MockGen. DO NOT EDIT.
// Source: internals/identity/interfaces/identity_service.go
//
// Generated by this command:
//
//	mockgen -source=internals/identity/interfaces/identity_service.go -destination=internals/identity/mocks/identity_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	identityv1 "github.com/ralvescosta/costa-financial-assistant/backend/protos/generated/identity/v1"
	onboardingv1 "github.com/ralvescosta/costa-financial-assistant/backend/protos/generated/onboarding/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenService is a mock of TokenService interface.
type MockTokenService struct {
	ctrl     *gomock.Controller
	recorder *MockTokenServiceMockRecorder
	isgomock struct{}
}

// MockTokenServiceMockRecorder is the mock recorder for MockTokenService.
type MockTokenServiceMockRecorder struct {
	mock *MockTokenService
}

// NewMockTokenService creates a new mock instance.
func NewMockTokenService(ctrl *gomock.Controller) *MockTokenService {
	mock := &MockTokenService{ctrl: ctrl}
	mock.recorder = &MockTokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenService) EXPECT() *MockTokenServiceMockRecorder {
	return m.recorder
}

// GetJwksMetadata mocks base method.
func (m *MockTokenService) GetJwksMetadata(ctx context.Context) (*identityv1.JwksMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJwksMetadata", ctx)
	ret0, _ := ret[0].(*identityv1.JwksMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJwksMetadata indicates an expected call of GetJwksMetadata.
func (mr *MockTokenServiceMockRecorder) GetJwksMetadata(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJwksMetadata", reflect.TypeOf((*MockTokenService)(nil).GetJwksMetadata), ctx)
}

// IssueBootstrapToken mocks base method.
func (m *MockTokenService) IssueBootstrapToken(ctx context.Context, userID, projectID, role string) (string, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueBootstrapToken", ctx, userID, projectID, role)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IssueBootstrapToken indicates an expected call of IssueBootstrapToken.
func (mr *MockTokenServiceMockRecorder) IssueBootstrapToken(ctx, userID, projectID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueBootstrapToken", reflect.TypeOf((*MockTokenService)(nil).IssueBootstrapToken), ctx, userID, projectID, role)
}

// ValidateToken mocks base method.
func (m *MockTokenService) ValidateToken(ctx context.Context, token string) (bool, *identityv1.JwtClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", ctx, token)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*identityv1.JwtClaims)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockTokenServiceMockRecorder) ValidateToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockTokenService)(nil).ValidateToken), ctx, token)
}

// MockIdentityRepository is a mock of IdentityRepository interface.
type MockIdentityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityRepositoryMockRecorder
	isgomock struct{}
}

// MockIdentityRepositoryMockRecorder is the mock recorder for MockIdentityRepository.
type MockIdentityRepositoryMockRecorder struct {
	mock *MockIdentityRepository
}

// NewMockIdentityRepository creates a new mock instance.
func NewMockIdentityRepository(ctrl *gomock.Controller) *MockIdentityRepository {
	mock := &MockIdentityRepository{ctrl: ctrl}
	mock.recorder = &MockIdentityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityRepository) EXPECT() *MockIdentityRepositoryMockRecorder {
	return m.recorder
}

// FindProjectMember mocks base method.
func (m *MockIdentityRepository) FindProjectMember(ctx context.Context, projectID, userID string) (*onboardingv1.ProjectMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindProjectMember", ctx, projectID, userID)
	ret0, _ := ret[0].(*onboardingv1.ProjectMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindProjectMember indicates an expected call of FindProjectMember.
func (mr *MockIdentityRepositoryMockRecorder) FindProjectMember(ctx, projectID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindProjectMember", reflect.TypeOf((*MockIdentityRepository)(nil).FindProjectMember), ctx, projectID, userID)
}

// FindUserByID mocks base method.
func (m *MockIdentityRepository) FindUserByID(ctx context.Context, userID string) (*onboardingv1.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByID", ctx, userID)
	ret0, _ := ret[0].(*onboardingv1.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByID indicates an expected call of FindUserByID.
func (mr *MockIdentityRepositoryMockRecorder) FindUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByID", reflect.TypeOf((*MockIdentityRepository)(nil).FindUserByID), ctx, userID)
}
