// Code generated by MockGen. DO NOT EDIT.
// Source: internals/files/interfaces/bank_account_service.go
//
// Generated by this command:
//
//	mockgen -source=internals/files/interfaces/bank_account_service.go -destination=internals/files/mocks/bank_account_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	filesv1 "github.com/ralvescosta/costa-financial-assistant/backend/protos/generated/files/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockBankAccountService is a mock of BankAccountService interface.
type MockBankAccountService struct {
	ctrl     *gomock.Controller
	recorder *MockBankAccountServiceMockRecorder
	isgomock struct{}
}

// MockBankAccountServiceMockRecorder is the mock recorder for MockBankAccountService.
type MockBankAccountServiceMockRecorder struct {
	mock *MockBankAccountService
}

// NewMockBankAccountService creates a new mock instance.
func NewMockBankAccountService(ctrl *gomock.Controller) *MockBankAccountService {
	mock := &MockBankAccountService{ctrl: ctrl}
	mock.recorder = &MockBankAccountServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBankAccountService) EXPECT() *MockBankAccountServiceMockRecorder {
	return m.recorder
}

// CreateBankAccount mocks base method.
func (m *MockBankAccountService) CreateBankAccount(ctx context.Context, projectID, label, createdBy string) (*filesv1.BankAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBankAccount", ctx, projectID, label, createdBy)
	ret0, _ := ret[0].(*filesv1.BankAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBankAccount indicates an expected call of CreateBankAccount.
func (mr *MockBankAccountServiceMockRecorder) CreateBankAccount(ctx, projectID, label, createdBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBankAccount", reflect.TypeOf((*MockBankAccountService)(nil).CreateBankAccount), ctx, projectID, label, createdBy)
}

// DeleteBankAccount mocks base method.
func (m *MockBankAccountService) DeleteBankAccount(ctx context.Context, projectID, bankAccountID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBankAccount", ctx, projectID, bankAccountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBankAccount indicates an expected call of DeleteBankAccount.
func (mr *MockBankAccountServiceMockRecorder) DeleteBankAccount(ctx, projectID, bankAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBankAccount", reflect.TypeOf((*MockBankAccountService)(nil).DeleteBankAccount), ctx, projectID, bankAccountID)
}

// ListBankAccounts mocks base method.
func (m *MockBankAccountService) ListBankAccounts(ctx context.Context, projectID string) ([]*filesv1.BankAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBankAccounts", ctx, projectID)
	ret0, _ := ret[0].([]*filesv1.BankAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBankAccounts indicates an expected call of ListBankAccounts.
func (mr *MockBankAccountServiceMockRecorder) ListBankAccounts(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBankAccounts", reflect.TypeOf((*MockBankAccountService)(nil).ListBankAccounts), ctx, projectID)
}

// MockBankAccountRepository is a mock of BankAccountRepository interface.
type MockBankAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBankAccountRepositoryMockRecorder
	isgomock struct{}
}

// MockBankAccountRepositoryMockRecorder is the mock recorder for MockBankAccountRepository.
type MockBankAccountRepositoryMockRecorder struct {
	mock *MockBankAccountRepository
}

// NewMockBankAccountRepository creates a new mock instance.
func NewMockBankAccountRepository(ctrl *gomock.Controller) *MockBankAccountRepository {
	mock := &MockBankAccountRepository{ctrl: ctrl}
	mock.recorder = &MockBankAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBankAccountRepository) EXPECT() *MockBankAccountRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBankAccountRepository) Create(ctx context.Context, account *filesv1.BankAccount) (*filesv1.BankAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, account)
	ret0, _ := ret[0].(*filesv1.BankAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBankAccountRepositoryMockRecorder) Create(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBankAccountRepository)(nil).Create), ctx, account)
}

// Delete mocks base method.
func (m *MockBankAccountRepository) Delete(ctx context.Context, projectID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, projectID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBankAccountRepositoryMockRecorder) Delete(ctx, projectID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBankAccountRepository)(nil).Delete), ctx, projectID, id)
}

// FindByProjectAndID mocks base method.
func (m *MockBankAccountRepository) FindByProjectAndID(ctx context.Context, projectID, id string) (*filesv1.BankAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProjectAndID", ctx, projectID, id)
	ret0, _ := ret[0].(*filesv1.BankAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProjectAndID indicates an expected call of FindByProjectAndID.
func (mr *MockBankAccountRepositoryMockRecorder) FindByProjectAndID(ctx, projectID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProjectAndID", reflect.TypeOf((*MockBankAccountRepository)(nil).FindByProjectAndID), ctx, projectID, id)
}

// ListByProject mocks base method.
func (m *MockBankAccountRepository) ListByProject(ctx context.Context, projectID string) ([]*filesv1.BankAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByProject", ctx, projectID)
	ret0, _ := ret[0].([]*filesv1.BankAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByProject indicates an expected call of ListByProject.
func (mr *MockBankAccountRepositoryMockRecorder) ListByProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByProject", reflect.TypeOf((*MockBankAccountRepository)(nil).ListByProject), ctx, projectID)
}
