// Code generated by MockGen. DO NOT EDIT.
// Source: internals/files/interfaces/extraction_service.go
//
// Generated by this command:
//
//	mockgen -source=internals/files/interfaces/extraction_service.go -destination=internals/files/mocks/extraction_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	filesv1 "github.com/ralvescosta/costa-financial-assistant/backend/protos/generated/files/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockBillRecordRepository is a mock of BillRecordRepository interface.
type MockBillRecordRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBillRecordRepositoryMockRecorder
	isgomock struct{}
}

// MockBillRecordRepositoryMockRecorder is the mock recorder for MockBillRecordRepository.
type MockBillRecordRepositoryMockRecorder struct {
	mock *MockBillRecordRepository
}

// NewMockBillRecordRepository creates a new mock instance.
func NewMockBillRecordRepository(ctrl *gomock.Controller) *MockBillRecordRepository {
	mock := &MockBillRecordRepository{ctrl: ctrl}
	mock.recorder = &MockBillRecordRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBillRecordRepository) EXPECT() *MockBillRecordRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBillRecordRepository) Create(ctx context.Context, tx *sql.Tx, record *filesv1.BillRecord) (*filesv1.BillRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, record)
	ret0, _ := ret[0].(*filesv1.BillRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBillRecordRepositoryMockRecorder) Create(ctx, tx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBillRecordRepository)(nil).Create), ctx, tx, record)
}

// FindByProjectAndDocumentID mocks base method.
func (m *MockBillRecordRepository) FindByProjectAndDocumentID(ctx context.Context, projectID, documentID string) (*filesv1.BillRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProjectAndDocumentID", ctx, projectID, documentID)
	ret0, _ := ret[0].(*filesv1.BillRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProjectAndDocumentID indicates an expected call of FindByProjectAndDocumentID.
func (mr *MockBillRecordRepositoryMockRecorder) FindByProjectAndDocumentID(ctx, projectID, documentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProjectAndDocumentID", reflect.TypeOf((*MockBillRecordRepository)(nil).FindByProjectAndDocumentID), ctx, projectID, documentID)
}

// MockStatementRecordRepository is a mock of StatementRecordRepository interface.
type MockStatementRecordRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStatementRecordRepositoryMockRecorder
	isgomock struct{}
}

// MockStatementRecordRepositoryMockRecorder is the mock recorder for MockStatementRecordRepository.
type MockStatementRecordRepositoryMockRecorder struct {
	mock *MockStatementRecordRepository
}

// NewMockStatementRecordRepository creates a new mock instance.
func NewMockStatementRecordRepository(ctrl *gomock.Controller) *MockStatementRecordRepository {
	mock := &MockStatementRecordRepository{ctrl: ctrl}
	mock.recorder = &MockStatementRecordRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatementRecordRepository) EXPECT() *MockStatementRecordRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStatementRecordRepository) Create(ctx context.Context, tx *sql.Tx, record *filesv1.StatementRecord) (*filesv1.StatementRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, record)
	ret0, _ := ret[0].(*filesv1.StatementRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockStatementRecordRepositoryMockRecorder) Create(ctx, tx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStatementRecordRepository)(nil).Create), ctx, tx, record)
}

// FindByProjectAndDocumentID mocks base method.
func (m *MockStatementRecordRepository) FindByProjectAndDocumentID(ctx context.Context, projectID, documentID string) (*filesv1.StatementRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProjectAndDocumentID", ctx, projectID, documentID)
	ret0, _ := ret[0].(*filesv1.StatementRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProjectAndDocumentID indicates an expected call of FindByProjectAndDocumentID.
func (mr *MockStatementRecordRepositoryMockRecorder) FindByProjectAndDocumentID(ctx, projectID, documentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProjectAndDocumentID", reflect.TypeOf((*MockStatementRecordRepository)(nil).FindByProjectAndDocumentID), ctx, projectID, documentID)
}
