// Code generated by MockGen. DO NOT EDIT.
// Source: internals/files/interfaces/document_service.go
//
// Generated by this command:
//
//	mockgen -source=internals/files/interfaces/document_service.go -destination=internals/files/mocks/files_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	interfaces "github.com/ralvescosta/costa-financial-assistant/backend/internals/files/interfaces"
	filesv1 "github.com/ralvescosta/costa-financial-assistant/backend/protos/generated/files/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockDocumentService is a mock of DocumentService interface.
type MockDocumentService struct {
	ctrl     *gomock.Controller
	recorder *MockDocumentServiceMockRecorder
	isgomock struct{}
}

// MockDocumentServiceMockRecorder is the mock recorder for MockDocumentService.
type MockDocumentServiceMockRecorder struct {
	mock *MockDocumentService
}

// NewMockDocumentService creates a new mock instance.
func NewMockDocumentService(ctrl *gomock.Controller) *MockDocumentService {
	mock := &MockDocumentService{ctrl: ctrl}
	mock.recorder = &MockDocumentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDocumentService) EXPECT() *MockDocumentServiceMockRecorder {
	return m.recorder
}

// ClassifyDocument mocks base method.
func (m *MockDocumentService) ClassifyDocument(ctx context.Context, projectID, documentID string, kind filesv1.DocumentKind) (*filesv1.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClassifyDocument", ctx, projectID, documentID, kind)
	ret0, _ := ret[0].(*filesv1.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClassifyDocument indicates an expected call of ClassifyDocument.
func (mr *MockDocumentServiceMockRecorder) ClassifyDocument(ctx, projectID, documentID, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClassifyDocument", reflect.TypeOf((*MockDocumentService)(nil).ClassifyDocument), ctx, projectID, documentID, kind)
}

// GetDocument mocks base method.
func (m *MockDocumentService) GetDocument(ctx context.Context, projectID, documentID string) (*filesv1.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDocument", ctx, projectID, documentID)
	ret0, _ := ret[0].(*filesv1.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDocument indicates an expected call of GetDocument.
func (mr *MockDocumentServiceMockRecorder) GetDocument(ctx, projectID, documentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDocument", reflect.TypeOf((*MockDocumentService)(nil).GetDocument), ctx, projectID, documentID)
}

// ListDocuments mocks base method.
func (m *MockDocumentService) ListDocuments(ctx context.Context, projectID string, pageSize int32, pageToken string) ([]*filesv1.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDocuments", ctx, projectID, pageSize, pageToken)
	ret0, _ := ret[0].([]*filesv1.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDocuments indicates an expected call of ListDocuments.
func (mr *MockDocumentServiceMockRecorder) ListDocuments(ctx, projectID, pageSize, pageToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDocuments", reflect.TypeOf((*MockDocumentService)(nil).ListDocuments), ctx, projectID, pageSize, pageToken)
}

// UploadDocument mocks base method.
func (m *MockDocumentService) UploadDocument(ctx context.Context, req *interfaces.UploadDocumentInput) (*filesv1.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadDocument", ctx, req)
	ret0, _ := ret[0].(*filesv1.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadDocument indicates an expected call of UploadDocument.
func (mr *MockDocumentServiceMockRecorder) UploadDocument(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadDocument", reflect.TypeOf((*MockDocumentService)(nil).UploadDocument), ctx, req)
}

// MockExtractionService is a mock of ExtractionService interface.
type MockExtractionService struct {
	ctrl     *gomock.Controller
	recorder *MockExtractionServiceMockRecorder
	isgomock struct{}
}

// MockExtractionServiceMockRecorder is the mock recorder for MockExtractionService.
type MockExtractionServiceMockRecorder struct {
	mock *MockExtractionService
}

// NewMockExtractionService creates a new mock instance.
func NewMockExtractionService(ctrl *gomock.Controller) *MockExtractionService {
	mock := &MockExtractionService{ctrl: ctrl}
	mock.recorder = &MockExtractionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtractionService) EXPECT() *MockExtractionServiceMockRecorder {
	return m.recorder
}

// GetDocumentDetail mocks base method.
func (m *MockExtractionService) GetDocumentDetail(ctx context.Context, projectID, documentID string) (*filesv1.Document, *filesv1.BillRecord, *filesv1.StatementRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDocumentDetail", ctx, projectID, documentID)
	ret0, _ := ret[0].(*filesv1.Document)
	ret1, _ := ret[1].(*filesv1.BillRecord)
	ret2, _ := ret[2].(*filesv1.StatementRecord)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetDocumentDetail indicates an expected call of GetDocumentDetail.
func (mr *MockExtractionServiceMockRecorder) GetDocumentDetail(ctx, projectID, documentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDocumentDetail", reflect.TypeOf((*MockExtractionService)(nil).GetDocumentDetail), ctx, projectID, documentID)
}

// ProcessDocument mocks base method.
func (m *MockExtractionService) ProcessDocument(ctx context.Context, jobID, projectID, documentID string, kind filesv1.DocumentKind) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessDocument", ctx, jobID, projectID, documentID, kind)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessDocument indicates an expected call of ProcessDocument.
func (mr *MockExtractionServiceMockRecorder) ProcessDocument(ctx, jobID, projectID, documentID, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessDocument", reflect.TypeOf((*MockExtractionService)(nil).ProcessDocument), ctx, jobID, projectID, documentID, kind)
}

// MockDocumentRepository is a mock of DocumentRepository interface.
type MockDocumentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDocumentRepositoryMockRecorder
	isgomock struct{}
}

// MockDocumentRepositoryMockRecorder is the mock recorder for MockDocumentRepository.
type MockDocumentRepositoryMockRecorder struct {
	mock *MockDocumentRepository
}

// NewMockDocumentRepository creates a new mock instance.
func NewMockDocumentRepository(ctrl *gomock.Controller) *MockDocumentRepository {
	mock := &MockDocumentRepository{ctrl: ctrl}
	mock.recorder = &MockDocumentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDocumentRepository) EXPECT() *MockDocumentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDocumentRepository) Create(ctx context.Context, tx *sql.Tx, doc *filesv1.Document) (*filesv1.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, doc)
	ret0, _ := ret[0].(*filesv1.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDocumentRepositoryMockRecorder) Create(ctx, tx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDocumentRepository)(nil).Create), ctx, tx, doc)
}

// FindByProjectAndHash mocks base method.
func (m *MockDocumentRepository) FindByProjectAndHash(ctx context.Context, projectID, hash string) (*filesv1.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProjectAndHash", ctx, projectID, hash)
	ret0, _ := ret[0].(*filesv1.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProjectAndHash indicates an expected call of FindByProjectAndHash.
func (mr *MockDocumentRepositoryMockRecorder) FindByProjectAndHash(ctx, projectID, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProjectAndHash", reflect.TypeOf((*MockDocumentRepository)(nil).FindByProjectAndHash), ctx, projectID, hash)
}

// FindByProjectAndID mocks base method.
func (m *MockDocumentRepository) FindByProjectAndID(ctx context.Context, projectID, id string) (*filesv1.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProjectAndID", ctx, projectID, id)
	ret0, _ := ret[0].(*filesv1.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProjectAndID indicates an expected call of FindByProjectAndID.
func (mr *MockDocumentRepositoryMockRecorder) FindByProjectAndID(ctx, projectID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProjectAndID", reflect.TypeOf((*MockDocumentRepository)(nil).FindByProjectAndID), ctx, projectID, id)
}

// ListByProject mocks base method.
func (m *MockDocumentRepository) ListByProject(ctx context.Context, projectID string, pageSize int32, offsetToken string) ([]*filesv1.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByProject", ctx, projectID, pageSize, offsetToken)
	ret0, _ := ret[0].([]*filesv1.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByProject indicates an expected call of ListByProject.
func (mr *MockDocumentRepositoryMockRecorder) ListByProject(ctx, projectID, pageSize, offsetToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByProject", reflect.TypeOf((*MockDocumentRepository)(nil).ListByProject), ctx, projectID, pageSize, offsetToken)
}

// UpdateKind mocks base method.
func (m *MockDocumentRepository) UpdateKind(ctx context.Context, tx *sql.Tx, projectID, id string, kind filesv1.DocumentKind) (*filesv1.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKind", ctx, tx, projectID, id, kind)
	ret0, _ := ret[0].(*filesv1.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateKind indicates an expected call of UpdateKind.
func (mr *MockDocumentRepositoryMockRecorder) UpdateKind(ctx, tx, projectID, id, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKind", reflect.TypeOf((*MockDocumentRepository)(nil).UpdateKind), ctx, tx, projectID, id, kind)
}

// MockAnalysisJobRepository is a mock of AnalysisJobRepository interface.
type MockAnalysisJobRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAnalysisJobRepositoryMockRecorder
	isgomock struct{}
}

// MockAnalysisJobRepositoryMockRecorder is the mock recorder for MockAnalysisJobRepository.
type MockAnalysisJobRepositoryMockRecorder struct {
	mock *MockAnalysisJobRepository
}

// NewMockAnalysisJobRepository creates a new mock instance.
func NewMockAnalysisJobRepository(ctrl *gomock.Controller) *MockAnalysisJobRepository {
	mock := &MockAnalysisJobRepository{ctrl: ctrl}
	mock.recorder = &MockAnalysisJobRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalysisJobRepository) EXPECT() *MockAnalysisJobRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAnalysisJobRepository) Create(ctx context.Context, tx *sql.Tx, job *filesv1.AnalysisJob) (*filesv1.AnalysisJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, job)
	ret0, _ := ret[0].(*filesv1.AnalysisJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAnalysisJobRepositoryMockRecorder) Create(ctx, tx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAnalysisJobRepository)(nil).Create), ctx, tx, job)
}

// FindByDocumentID mocks base method.
func (m *MockAnalysisJobRepository) FindByDocumentID(ctx context.Context, projectID, documentID string) (*filesv1.AnalysisJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByDocumentID", ctx, projectID, documentID)
	ret0, _ := ret[0].(*filesv1.AnalysisJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByDocumentID indicates an expected call of FindByDocumentID.
func (mr *MockAnalysisJobRepositoryMockRecorder) FindByDocumentID(ctx, projectID, documentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByDocumentID", reflect.TypeOf((*MockAnalysisJobRepository)(nil).FindByDocumentID), ctx, projectID, documentID)
}

// UpdateDocumentAnalysisStatus mocks base method.
func (m *MockAnalysisJobRepository) UpdateDocumentAnalysisStatus(ctx context.Context, tx *sql.Tx, projectID, documentID, analysisStatus, failureReason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDocumentAnalysisStatus", ctx, tx, projectID, documentID, analysisStatus, failureReason)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDocumentAnalysisStatus indicates an expected call of UpdateDocumentAnalysisStatus.
func (mr *MockAnalysisJobRepositoryMockRecorder) UpdateDocumentAnalysisStatus(ctx, tx, projectID, documentID, analysisStatus, failureReason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDocumentAnalysisStatus", reflect.TypeOf((*MockAnalysisJobRepository)(nil).UpdateDocumentAnalysisStatus), ctx, tx, projectID, documentID, analysisStatus, failureReason)
}

// UpdateStatus mocks base method.
func (m *MockAnalysisJobRepository) UpdateStatus(ctx context.Context, tx *sql.Tx, jobID, status, lastError string, attemptCount int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, tx, jobID, status, lastError, attemptCount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockAnalysisJobRepositoryMockRecorder) UpdateStatus(ctx, tx, jobID, status, lastError, attemptCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockAnalysisJobRepository)(nil).UpdateStatus), ctx, tx, jobID, status, lastError, attemptCount)
}
