// Code generated by MockGen. DO NOT EDIT.
// Source: internals/bills/interfaces/payment_service.go
//
// Generated by this command:
//
//	mockgen -source=internals/bills/interfaces/payment_service.go -destination=internals/bills/mocks/payment_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	billsv1 "github.com/ralvescosta/costa-financial-assistant/backend/protos/generated/bills/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockBillPaymentService is a mock of BillPaymentService interface.
type MockBillPaymentService struct {
	ctrl     *gomock.Controller
	recorder *MockBillPaymentServiceMockRecorder
	isgomock struct{}
}

// MockBillPaymentServiceMockRecorder is the mock recorder for MockBillPaymentService.
type MockBillPaymentServiceMockRecorder struct {
	mock *MockBillPaymentService
}

// NewMockBillPaymentService creates a new mock instance.
func NewMockBillPaymentService(ctrl *gomock.Controller) *MockBillPaymentService {
	mock := &MockBillPaymentService{ctrl: ctrl}
	mock.recorder = &MockBillPaymentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBillPaymentService) EXPECT() *MockBillPaymentServiceMockRecorder {
	return m.recorder
}

// GetBill mocks base method.
func (m *MockBillPaymentService) GetBill(ctx context.Context, projectID, billID string) (*billsv1.BillRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBill", ctx, projectID, billID)
	ret0, _ := ret[0].(*billsv1.BillRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBill indicates an expected call of GetBill.
func (mr *MockBillPaymentServiceMockRecorder) GetBill(ctx, projectID, billID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBill", reflect.TypeOf((*MockBillPaymentService)(nil).GetBill), ctx, projectID, billID)
}

// GetPaymentDashboard mocks base method.
func (m *MockBillPaymentService) GetPaymentDashboard(ctx context.Context, projectID, cycleStart, cycleEnd string, pageSize int32, pageToken string) ([]*billsv1.PaymentDashboardEntry, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentDashboard", ctx, projectID, cycleStart, cycleEnd, pageSize, pageToken)
	ret0, _ := ret[0].([]*billsv1.PaymentDashboardEntry)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPaymentDashboard indicates an expected call of GetPaymentDashboard.
func (mr *MockBillPaymentServiceMockRecorder) GetPaymentDashboard(ctx, projectID, cycleStart, cycleEnd, pageSize, pageToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentDashboard", reflect.TypeOf((*MockBillPaymentService)(nil).GetPaymentDashboard), ctx, projectID, cycleStart, cycleEnd, pageSize, pageToken)
}

// ListBills mocks base method.
func (m *MockBillPaymentService) ListBills(ctx context.Context, projectID string, status billsv1.PaymentStatus, pageSize int32, pageToken string) ([]*billsv1.BillRecord, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBills", ctx, projectID, status, pageSize, pageToken)
	ret0, _ := ret[0].([]*billsv1.BillRecord)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListBills indicates an expected call of ListBills.
func (mr *MockBillPaymentServiceMockRecorder) ListBills(ctx, projectID, status, pageSize, pageToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBills", reflect.TypeOf((*MockBillPaymentService)(nil).ListBills), ctx, projectID, status, pageSize, pageToken)
}

// MarkBillPaid mocks base method.
func (m *MockBillPaymentService) MarkBillPaid(ctx context.Context, projectID, billID, markedBy string) (*billsv1.BillRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkBillPaid", ctx, projectID, billID, markedBy)
	ret0, _ := ret[0].(*billsv1.BillRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkBillPaid indicates an expected call of MarkBillPaid.
func (mr *MockBillPaymentServiceMockRecorder) MarkBillPaid(ctx, projectID, billID, markedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkBillPaid", reflect.TypeOf((*MockBillPaymentService)(nil).MarkBillPaid), ctx, projectID, billID, markedBy)
}

// MockBillPaymentRepository is a mock of BillPaymentRepository interface.
type MockBillPaymentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBillPaymentRepositoryMockRecorder
	isgomock struct{}
}

// MockBillPaymentRepositoryMockRecorder is the mock recorder for MockBillPaymentRepository.
type MockBillPaymentRepositoryMockRecorder struct {
	mock *MockBillPaymentRepository
}

// NewMockBillPaymentRepository creates a new mock instance.
func NewMockBillPaymentRepository(ctrl *gomock.Controller) *MockBillPaymentRepository {
	mock := &MockBillPaymentRepository{ctrl: ctrl}
	mock.recorder = &MockBillPaymentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBillPaymentRepository) EXPECT() *MockBillPaymentRepositoryMockRecorder {
	return m.recorder
}

// FindIdempotencyKey mocks base method.
func (m *MockBillPaymentRepository) FindIdempotencyKey(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindIdempotencyKey", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindIdempotencyKey indicates an expected call of FindIdempotencyKey.
func (mr *MockBillPaymentRepositoryMockRecorder) FindIdempotencyKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindIdempotencyKey", reflect.TypeOf((*MockBillPaymentRepository)(nil).FindIdempotencyKey), ctx, key)
}

// GetBill mocks base method.
func (m *MockBillPaymentRepository) GetBill(ctx context.Context, projectID, billID string) (*billsv1.BillRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBill", ctx, projectID, billID)
	ret0, _ := ret[0].(*billsv1.BillRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBill indicates an expected call of GetBill.
func (mr *MockBillPaymentRepositoryMockRecorder) GetBill(ctx, projectID, billID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBill", reflect.TypeOf((*MockBillPaymentRepository)(nil).GetBill), ctx, projectID, billID)
}

// GetDashboardEntries mocks base method.
func (m *MockBillPaymentRepository) GetDashboardEntries(ctx context.Context, projectID, cycleStart, cycleEnd string, pageSize int32, pageToken string) ([]*billsv1.PaymentDashboardEntry, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDashboardEntries", ctx, projectID, cycleStart, cycleEnd, pageSize, pageToken)
	ret0, _ := ret[0].([]*billsv1.PaymentDashboardEntry)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDashboardEntries indicates an expected call of GetDashboardEntries.
func (mr *MockBillPaymentRepositoryMockRecorder) GetDashboardEntries(ctx, projectID, cycleStart, cycleEnd, pageSize, pageToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDashboardEntries", reflect.TypeOf((*MockBillPaymentRepository)(nil).GetDashboardEntries), ctx, projectID, cycleStart, cycleEnd, pageSize, pageToken)
}

// ListBills mocks base method.
func (m *MockBillPaymentRepository) ListBills(ctx context.Context, projectID string, status billsv1.PaymentStatus, pageSize int32, pageToken string) ([]*billsv1.BillRecord, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBills", ctx, projectID, status, pageSize, pageToken)
	ret0, _ := ret[0].([]*billsv1.BillRecord)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListBills indicates an expected call of ListBills.
func (mr *MockBillPaymentRepositoryMockRecorder) ListBills(ctx, projectID, status, pageSize, pageToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBills", reflect.TypeOf((*MockBillPaymentRepository)(nil).ListBills), ctx, projectID, status, pageSize, pageToken)
}

// MarkPaid mocks base method.
func (m *MockBillPaymentRepository) MarkPaid(ctx context.Context, projectID, billID, markedBy string) (*billsv1.BillRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPaid", ctx, projectID, billID, markedBy)
	ret0, _ := ret[0].(*billsv1.BillRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkPaid indicates an expected call of MarkPaid.
func (mr *MockBillPaymentRepositoryMockRecorder) MarkPaid(ctx, projectID, billID, markedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPaid", reflect.TypeOf((*MockBillPaymentRepository)(nil).MarkPaid), ctx, projectID, billID, markedBy)
}

// StoreIdempotencyKey mocks base method.
func (m *MockBillPaymentRepository) StoreIdempotencyKey(ctx context.Context, key, service, payload string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreIdempotencyKey", ctx, key, service, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreIdempotencyKey indicates an expected call of StoreIdempotencyKey.
func (mr *MockBillPaymentRepositoryMockRecorder) StoreIdempotencyKey(ctx, key, service, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreIdempotencyKey", reflect.TypeOf((*MockBillPaymentRepository)(nil).StoreIdempotencyKey), ctx, key, service, payload)
}
